frontend/src/pages/CreateFeed/index.tsx
frontend/src/pages/CreateFeed/styles.scss

createfeed 페이지 스타일링 초안 마무리 지었음.
아직 ts 기능은 하나도 달지 않았음.

feat : createfeed 페이지 스타일링 초안 완료

---

frontend/src/pages/Posting/index.tsx
frontend/src/pages/Posting/styles.scss

posting 마크업 초안 완료

---

frontend/src/components/Toast/index.tsx
frontend/src/components/Toast/styles.scss
frontend/src/pages/Feed/index.tsx

feat : toastify 커스텀 완료

---

frontend/src/components/Header/index.tsx

Header 컴포넌트의 `React.memo` 를 추가하였습니다.

refactor : 컴포넌트 재렌더링 방지 위한 React.memo 추가

---

frontend/src/pages/Write/index.tsx

- 이미지 업로드 후, 새로운 이미지를 업로드 했을 때, 기존의 이미지가 삭제되던 현상 해결 
- 이를 위해 `map()` 을 `forEach()` 로 수정하였고, `imageUrlLists` 에 `push` 하는 로직으로 변경
- 컴포넌트 함수명 통일
- 기존엔 `on~~` `handle~~` 등 네이밍이 중구난방하였으나 [이 페이지](https://sustainable-dev.tistory.com/101)를 참고해 변경

fix : write 페이지 오류 수정

---

backend/src/customDecorator/feed.decorator.ts
backend/src/error/httpException.ts
backend/src/error/serverError.ts
backend/src/feed/feed.controller.ts
backend/src/feed/feed.service.ts
backend/src/users/dto/join.cookie.dto.ts
backend/src/users/users.controller.ts
backend/src/users/users.service.ts

그룹 피드 수정 api 를 추가하였다.
close #39

그룹 피드 수정 api 추가

---

backend/src/users/dto/join.nickname.dto.ts
backend/src/validation.ts

기존의 validation pipe에서 단일 key값이 아닌, message array로 error를 구분하던 부분을 수정하였다.
: `transform` 오버라이딩에서 `createExceptionFactory` 오버라이딩으로 수정
close #55

custom validation pipe 하드코딩 수정

---

backend/src/entities/Comment.entity.ts
backend/src/entities/Feed.entity.ts
backend/src/entities/Image.entity.ts
backend/src/entities/Like.entity.ts
backend/src/entities/Posting.entity.ts
backend/src/entities/User.entity.ts
backend/src/entities/UserFeedMapping.entity.ts
backend/src/entities/entityInterfaces/CommentInterface.ts
backend/src/entities/entityInterfaces/FeedInterface.ts
backend/src/entities/entityInterfaces/ImageInterface.ts
backend/src/entities/entityInterfaces/PostingInterface.ts
backend/src/entities/entityInterfaces/UserInterface.ts
backend/src/users/users.service.ts

entity들이 서로 맵핑 연관관계에 있는 경우 순환참조가 발생한다.
따라서 아래 링크를 참고하여, 각 엔티티 별 interface를 만들고, 연관관계 참조에는 이 interface를 참조하도록 하였다.
https://github.com/typeorm/typeorm/issues/4190

Entity 순환 참조 해결

---

frontend/.eslintrc.js
frontend/.gitignore
frontend/src/index.tsx
frontend/src/pages/OAuth/index.tsx
frontend/src/pages/SignIn/index.tsx
frontend/src/pages/SignIn/style.scss

- 한 일
로그인 버튼 누르면 카카오 로그인 페이지로 리다이렉트
정상적으로 로그인 성공하면 리다이렉트 페이지에서 코드 받아오고 api 호출 (추후 백엔드 서버 열리면 제대로 연결 예정)
- 이슈 #69

feat : 로그인 기능 초반 구현 (추후 api 연결 필요)

---

frontend/src/components/SigninBackground/index.tsx
frontend/src/components/SigninBackground/style.scss
frontend/src/global.scss
frontend/src/pages/Info/index.tsx
frontend/src/pages/Info/style.scss
frontend/src/pages/SignIn/index.tsx
frontend/src/pages/SignIn/style.scss
frontend/src/util/validation/bool.ts

* background를 컴포넌트로 작성함으로 인한 수정사항 반영
* Signin의 배경을 컴포넌트로 분리
* 컴포넌트로 분리한 배경을 signin,info 페이지에 반영
* 유효성 검사를 위한 bool.ts 초안 작성

Feat/snow background/fe/gh

---

.github/workflows/backend-ci.yml
backend/src/feed/feed.controller.ts
backend/src/feed/feed.service.ts

eslint 검사에서 계속 오류가 발생하여 일시적으로 끄고 ci-cd를 진행한다

fix: lint 일시 중지

---

frontend/.prettierrc
frontend/src/pages/CreateFeed/GroupMember/Suggestions.tsx
frontend/src/pages/CreateFeed/GroupMember/index.tsx
frontend/src/pages/CreateFeed/index.tsx
frontend/src/pages/CreateFeed/types.ts
frontend/src/util/fetcher.ts

Feat/createfeed suggestion/fe/gh

---

backend/package-lock.json
backend/package.json
backend/src/app.module.ts
backend/src/image/image.controller.spec.ts
backend/src/image/image.controller.ts
backend/src/image/image.module.ts
backend/src/image/image.service.spec.ts
backend/src/image/image.service.ts

- `/image` 로 이미지 파일 리스트가 담긴 `formData` 를 `POST` 로 보내면, 해당 파일 리스트를 오브젝트 스토리지에 업로드한 후, 오브젝트 스토리지 내의 파일 URL을 반환한다. 
- 해당 기능을 구현하기 위해 `multer` 라는 라이브러리를 사용했으며, `NCP` 의 `Object Storage` 에 접근하기 위해 `aws-sdk` 라이브러리를 사용하였다.

feat : 이미지 오브젝트 스토리지 업로드 API 구현

---

frontend/src/hooks/usePost.tsx
frontend/src/pages/Write/index.tsx

- write 페이지에서 업로드 버튼을 누르면 이미지 리스트가 전송된다. 
- 오브젝트 스토리지에 업로드가 성공하면, 이미지 url 리스트를 `response.data` 로 받는다.

write 페이지에서 오브젝트 스토리지 업로드 기능 구현 

---

backend/src/feed/feed.controller.ts
backend/src/feed/feed.service.ts

피드 정보 조회 api 추가

---

frontend/src/pages/Feeds/CreateFeedButton/index.tsx
frontend/src/pages/Feeds/index.tsx

* 피드 생성버튼 컴포넌트로 분리
* 피드 목록 작성완료

Feat/feeds show feeds/fe/gh

---

frontend/src/index.tsx
frontend/src/pages/Error/index.tsx
frontend/src/pages/Error/style.scss

클라이언트에서 지정하지 않은 경로에 접근시 커스텀한 404 에러페이지를 리턴한다.

feat : 에러페이지 추가

---

backend/src/ServerErrorHandlingFilter.ts
backend/src/feed/feed.controller.ts
backend/src/users/users.controller.ts
backend/src/users/users.service.ts

- 닉네임 중복 검사 여부 api 를 만들었다
- 닉네임으로 유저 검색하여 해당하는 유저 리스트를 내려주는 api에서, 검색결과에서 본인은 제외하도록 하였다.
close #118  #117

닉네임 중복 여부 검사 api

---

frontend/.eslintrc.js
frontend/public/index.html
frontend/react-app-env.d.ts
frontend/src/pages/Feed/FeedProfile/index.tsx
frontend/tsconfig.json

#133
- 카카오로 공유하기 기능을 구현하였습니다. 
- 메시지 템플릿을 설정하였습니다.
- 출처 링크를 `/feed` 로 설정하였으나, 추후 분기처리 후 재설정이 필요합니다.

[FE/Feat] 카카오 공유하기 기능 구현 

---

backend/src/feed/feed.service.ts
backend/src/posting/posting.controller.ts

innerJoinSelect 를 InnerJoin, Select 으로 변경 
이렇게 한 이유는, innerJoinSelct를 할경우, select해와야할 컬럼 외에도 불필요한 정보들을 다 가져오기 때문에 이를 분리해서 InnerJoin, select 로 분리함.

[Refactor] queryBuilder 수정 

---

backend/src/feed/dto/info.feed.dto.ts
backend/src/feed/feed.service.ts

포스팅 무한 스크롤 api 의 결과에 `postingCnt` 필드를 추가해 총 포스팅 수를 내려줍니다.

피드 정보 api 수정

---

frontend/src/pages/Write/index.tsx
frontend/src/pages/Write/style.scss
frontend/src/util/cropImg/index.tsx

* 이미지를 정사각형으로 잘라주는 cropImg 함수 작성
* 썸네일 생성시 cropImg를 통해 정사각형으로 자르도록 수정

Feat/crop image/fe/gh

---

backend/src/feed/dto/info.feed.dto.ts
backend/src/feed/feed.controller.ts
backend/src/feed/feed.service.ts

피드 조회 api 에 피드 주인 여부인지 나타내는 "isOwner" 항목을 추가하였다.

피드 조회 api : 피드 주인 여부 내려주도록 변경

---

backend/src/common/filters/ServerErrorHandlingFilter.ts
backend/src/common/guard/DueDate.guard.ts
backend/src/common/guard/refreshtoken.guard.ts
backend/src/posting/posting.controller.ts
backend/src/users/users.service.ts

에러 핸들링 로직 main 머지 관련 반영이 잘 안된 버그가 있어서 수정을 하고,
userService에서 추가적으로 불필요한 try..catch문을 제거하였습니다.

에러 핸들링 수정 로직 충돌 해결 및 리팩터링

---

backend/src/common/filters/ServerErrorHandlingFilter.ts
backend/src/common/guard/accesstoken.guard.ts
backend/src/custom/customError/serverError.ts
backend/src/feed/dto/request/feed.scroll.dto.ts

기존에 비로그인 시 에러를 던지던 로그인 유무 api를 정상 응답(data:false) 로 내려주도록 수정하였다.

로그인 유무 응답 api 수정

---

backend/src/common/guard/DueDate.guard.ts
backend/src/common/guard/accesstoken.guard.ts
backend/src/main.ts

모든 api 주소 앞에 `/api` 를 추가하였습니다.
closed #166

refactor: 모든 주소 앞에 /api 추가

---

backend/src/app.controller.ts

현재 서버의 시간을 내려주는 api를 생성하였다
ex) http://localhost:3001/api/serverTime
closed #176

현재 서버 시간을 내려주는 api 생성

---

backend/src/feed/dto/info.feed.dto.ts
backend/src/feed/feed.service.ts

refactor: userinfo에 isGroupfeed 유무 반환

refactor: userinfo에 isGroupfeed 유무 반환

---

frontend/src/pages/Posting/ImageSlider/ImageCard.tsx
frontend/src/pages/Posting/ImageSlider/index.tsx
frontend/src/pages/Posting/ImageSlider/types.tsx
frontend/src/pages/Write/CreatePostingButton/index.tsx
frontend/src/pages/Write/ImageCards/index.tsx
frontend/src/pages/Write/ThumbnailPreview/index.tsx
frontend/src/pages/Write/index.tsx
frontend/src/pages/Write/types.ts

* 썸네일들을 보여주는 컴포넌트에서 Images 배열을 관리하도록 분리
* 버튼 컴포넌트 분리
* thumbnailpreview에서 썸네일을 생성하고, 보여주오록 관심사 분리
* write에서 사용하는 인터페이스 들을 types.ts에서 모아서 관리
+ 포스팅에서 Lqip + lazy loading 하는 로직 작성
(실수로 여기 브렌치에 올림,,,ㅜ)

Feat/write separate of concern/fe/gh

---

backend/src/posting/posting.module.ts
backend/src/posting/posting.repository.ts
backend/src/posting/posting.service.ts

posting Service 레이어에서 조금 더 비즈니스 로직에만 집중할 수 있도록 posting custom repository를 구현하여 레이어를 분리하는 작업을 진행함.

postingModule 부분 커스텀 레포지토리 적용

---

frontend/src/pages/Feed/FeedPostingList/index.tsx
frontend/src/pages/Feed/FeedProfile/index.tsx
frontend/src/util/index.ts

- 공개일이 지나면 글쓰기 버튼이 사라질 수 있도록 로직을 수정하였습니다.
- 남은 시간을 보여주는 로직에서 만약 59분이 남았다면 0일 0시간으로 보이는 문제를 발견
- 그때부터는 `${diffMinute}분 ${diffSecond}초`로 보일 수 있도록 형식을 바꾸었습니다.

fix : 공개일이 지나면 글쓰기 버튼 사라지게 수정, 남은 시간 로직 수정

---

.github/workflows/backend-cd.yml
backend/deploy.sh
backend/src/users/users.facade.ts

SourceDeploy의 API를 이용하여 build가 끝나면 자동으로 배포가 진행되도록 하였다.

SourceDeploy API를 활용한 배포 자동화

---

frontend/src/hooks/useInfiniteScroll.tsx
frontend/src/pages/Feed/FeedPostingList/ObserverElement/style.scss
frontend/src/pages/Feed/FeedPostingList/index.tsx

fix : feed 무한 스크롤 리버스 연동

---

backend/.gitignore
backend/package-lock.json
backend/package.json
backend/src/posting/posting.repository.ts
backend/src/users/users.controller.ts

소소한 베타테스트를 통해, 피드 조회 시 현재 유저의 nickname을 타 sns처럼 보여주는 기능을 추가하기로 했다.
이를 위해서, nickname을 반환하는 api를 생성하였다.
db 접근을 최소화하기 위하여, accessToken에 실린 user 정보를 단순히 반환해줌으로써, db 접근을 하지 않는다.
(로그인이 된 사용자만이 피드를 조회할 수 있으므로, 로그인 된 사용자만이 해당 api를 사용하는 것을 전제로 한다.)

닉네임 반환 api 생성

---

backend/src/common/guard/duedate.guard.ts
backend/src/entities/Image.entity.ts
backend/src/posting/decorators/create.posting.decorator.ts
backend/src/posting/dto/create.posting.dto.ts
backend/src/posting/posting.controller.ts
backend/src/posting/posting.repository.ts
backend/src/posting/posting.service.ts

- 기존에 controller 단에서 param, body, req에서 각각 인자를 들고 와서 createpostingDto를 만들어 주었는데,
이 로직을 customDecorator를 만들어주고 여기에 위임했다.
- createPosting에서 포스팅 등록 이미지들을 insert 해 주는 구문을 bulk insert로 수정하였다.
- createPosting에서 insert 후 불필요한 select 구문을 없애주었다.(`updateEntity(false)`)

feed repository 리팩터링

---

frontend/src/components/Header/index.tsx
frontend/src/components/Header/style.scss
frontend/src/global.scss
frontend/src/hooks/useInfiniteScroll.tsx
frontend/src/pages/CreateFeed/CreateFeedButton/index.tsx
frontend/src/pages/CreateFeed/style.scss
frontend/src/pages/EditFeed/EditFeedButton/index.tsx
frontend/src/pages/EditFeed/style.scss
frontend/src/pages/Feed/FeedPostingList/index.tsx
frontend/src/pages/SignIn/style.scss
frontend/src/pages/Write/CreatePostingButton/index.tsx
frontend/src/pages/Write/style.scss

페이지 쭉 둘러봤을 때 사용자 경험상 ui 고치면 좋을 것 같은 부분들을 수정하였습니다.
살펴보시고 이전이 나을 것 같다 생각되면 편하게 말씀 부탁드립니다~
- 헤더는 닉네임으로 고정인데, 이게 남의 피드에서도 내 닉네임이 보이니까 사용자 입장에서 조금 혼란스러울 수 있을 거란 생각이 들었습니다.
- 그래서 직관적으로 닉네임이라는걸 알 수 있게 인사 문구를 넣었는데, 이렇게 되면 최대 7글자~10글자...? 이상이 되면 말줄임표로 닉네임이 잘리게 됩니다.
이런식으로...
그래서 바꿔도 될지 고민이 드네요... 의견 부탁드려요
- 헤더를 상단부에 고정하였습니다.
- `포스팅 작성` , `피드 생성` , `피드 수정` 에 있는 버튼은 하단부에 고정하였습니다.
- 사파리에서의 스크롤 문제를 해결
- 무한 스크롤을 조금 더 부드럽게 볼 수 있도록 Observer Element를 삭제

[FE] UI 수정 

---

backend/src/feed/dto/info.feed.dto.ts
backend/src/feed/feed.controller.ts
backend/src/feed/feed.repository.ts
backend/src/feed/feed.service.ts
backend/src/feed/user.feed.mapping.repository.ts

feed Service layer의 부분을 리팩토링 하는 작업을 진행했습니다. 
기존의 Feed Service Layer 안의 transaction 안에는 많은 비즈니스 로직들이 담겨 있었는데, 해당 비즈니스 로직들을 각각의 커스텀 레포지토리에서 작업을 할 수 있도록  커스텀 레포지토리 안에 함수로 모듈화를 해두었고, service Layer 안에서는 해당 함수들(비즈니스 로직들을) 호출 하는 역할만을 수행할 수 있도록 관심사를 분리했습니다.

[Refactor] feed 서비스레이어 수정작업
