frontend/package-lock.json
frontend/package.json
frontend/src/pages/Write/ThumbnailPreview/index.tsx
frontend/src/pages/Write/ThumbnailPreview/style.scss
frontend/src/pages/Write/index.tsx
frontend/src/pages/Write/style.scss

-- | -- | --
이미지가 없으면 썸네일 미리보기 버튼 disabled  |  사진은 정사각형에 맞춰서 빈 공간은 검은색으로 나타난다. |  썸네일 미리보기 버튼을 누르면 8bit convert된 모달이 나타난다.

feat : 게시물 업로드 페이지 썸네일 미리보기 기능 추가 

---

frontend/src/global.scss
frontend/src/pages/Feeds/styles.scss
frontend/src/pages/Write/index.tsx
frontend/src/pages/Write/style.scss

-- | --
사진이 추가되지 않았을 경우 게시물 업로드하기 버튼이 `disabled` 되며, 사진을 추가하라는 안내 문구가 출력된다.  | 사진이 추가됏을 경우 게시물 업로드 하기 버튼이 `enable` 된다.   

feat : 사진을 추가하지 않았을 때 안내 문구, 버튼 disabled 기능 추가

---

frontend/src/global.scss
frontend/src/index.tsx
frontend/src/pages/Info/index.tsx
frontend/src/pages/Info/style.scss
frontend/src/pages/SignIn/style.scss
frontend/src/util/index.ts

* info 페이지 마크업 초안 완료
* global.scss의 input-common Mixin의 백그라운드를 투명으로 변경
* Info 페이지 테스를 위한 임시 라우팅 추가
* signin page의 배경을 global.scss의 mixin으로 변경
* useRef를 활용한 Input 태그 onChange 함수 생성

info 페이지 마크업 초안완료 및 코드 정리

---

backend/.eslintrc.js
backend/src/ServerErrorHandlingFilter.ts
backend/src/app.module.ts
backend/src/common/DueDate.guard.ts
backend/src/entities/Feed.entity.ts
backend/src/entities/Posting.entity.ts
backend/src/entities/entityInterfaces/FeedInterface.ts
backend/src/error/httpException.ts
backend/src/error/serverError.ts
backend/src/feed/feed.controller.ts
backend/src/feed/feed.service.ts
backend/src/posting/dto/find.posting.dto.ts
backend/src/posting/posting.controller.spec.ts
backend/src/posting/posting.controller.ts
backend/src/posting/posting.module.ts
backend/src/posting/posting.service.spec.ts
backend/src/posting/posting.service.ts

- `Feed` entity `Maxcount` 컬럼 삭제
- `Feed` entity `isGroupFeed{type: boolean}` 컬럼 추가
- GroupFeed MemeberList 2 이상 100 이하로 제한
기존에 Maxcount를 통하여 그룹/개인 피드 여부를 판별하였다.
(Maxcount=1이면 개인, 아니면 그룹)
이런 방식을 채택했던 이유는 피드의 현재 회원 수를 사용할 것이라고 생각해서였는데,
- 그룹 피드 UI에서 현재 멤버 수를 보여주지 않음
- 그룹 피드 수정 시 기존의 멤버 수를 사용하지 않음
등의 이유로, 그룹/개인 피드 여부를 구분하는 용도로만 쓰이게 되었다.
따라서 number보다 boolean 컬럼을 사용하는 것이 더 직관적이라 생각하여 수정하였다.

Feed entity `Maxcount` 컬럼 삭제 및 `isGroupFeed` 컬럼 추가

---

backend/src/common/authorization.spec.ts
backend/src/customValidationPipe.ts
backend/src/entities/Feed.entity.ts
backend/src/feed/feed.controller.spec.ts
backend/src/feed/feed.controller.ts

다음의 형식으로 422 HttpException을 내려주도록 수정하였다.
```
{
"success": false,
"code": 422,
"data": {
"isNotEmpty": "name should not be empty"
}
}
```

validationError 422 에러 메세지 포함하도록 수정

---

backend/src/entities/User.entity.ts
backend/src/users/dto/join.request.dto.ts

현재 nickname 컬럼에 full-text-index를 적용하여 `닉네임으로 회원 검색` 속도를 줄이고 있습니다.
그런데 nickname 컬럼은 unique constraint 역시 있어야 합니다.
그러나 한 컬럼에 2개의 index를 동시에 접목할 순 없으므로,
`nickname을 해시한 컬럼 hashedNickname을 추가하여 unique constraint는 이걸로 체크` 하도록 하였습니다.
왜 이 선택을 하였는지는 여기 써져 있습니다.
https://auspicious-tarsal-986.notion.site/MySQL-mocking-edd6f5700e7845e0b6a5ce2be2e23d7d
hash 함수는 md5을 사용하였습니다.
- User table에 hashedNickname(char, 32) 추가
- joinUserDto 에 hashedNickname 생성 함수 추가 및 `join` 로직 수정

Users 컬럼에 `hashedNickname` 컬럼 추가 및 join 로직 수정

---

backend/src/feed/feed.controller.ts

이전
```typescript
@Get('scroll/:feedId')
async getFeedPostingThumbnail(
@Param('feedId') encryptedId: string,
@Body('startPostingId')
startPostingId: number,
) {
const postingThumbnailList = await this.feedService.getPostingThumbnails(
encryptedId,
startPostingId,
);
return postingThumbnailList;
}
}
```
이후
```typescript
@Get('scroll/:feedId')
async getFeedPostingThumbnail(
@Param('feedId') encryptedId: string,
@Query('index') startPostingId: number,
) {
const postingThumbnailList = await this.feedService.getPostingThumbnails(
encryptedId,
startPostingId,
);
return ResponseEntity.OK_WITH_DATA(postingThumbnailList);
}
}
```
-  axios는 get에 body parameter를 넘겨줄 수 없다 -> 때문에 query 로 변경하였다.
- return 값을 responseEntity에 맞게 변경하였다.

fix : feed controller 수정

---

backend/src/users/users.controller.ts

이전
```typescript
@Post('join')
async joinUser(
...
return res.redirect('http://localhost:3000/feeds')
}
```
이후
```typescript
@Post('join')
async joinUser(
...
res.send(ResponseEntity.CREATED());
}
```
- 이전의 경우 계속 feeds 페이지로 리다이렉트 하는 것을 막았다. 그래서 에러를 리턴했다. 
ㄴ 이거 도대체 이유가 뭔지 모르겠음... cors 때문인 것 같긴 한데? 다른데는 되는데 왜 여기서만? ㅠㅠ 
- 이를 해결하기 위해
`return ResponseEntity.CREATED()` 로 변경 시도해보았으나 에러 반환 (BAD RESPONSE)
그래서 response entity를 `send` 하는 것으로 변경하였는데 
여기는 왜 칼럼들이 대문자로 시작할까요...?
nest 정말 어렵네요..

fix : user controller 수정

---

frontend/src/hooks/useInfiniteScroll.tsx
frontend/src/index.tsx

- 중첩 라우팅 경로 설정
각 포스팅을 `http://localhost:3000/feed/feed해쉬변수/포스팅번호` 로 접근 가능하게 구현
- 무한 스크롤 커스텀 훅 구현
intersection observer api를 사용해 무한 스크롤이 가능하도록 커스텀 훅을 구현하였다.

feat : 중첩 라우팅 경로 설정 및 무한 스크롤 훅 설정

---

frontend/src/pages/Write/index.tsx
frontend/src/util/cropImg/index.tsx

cropimg 함수를 기존에는 img 태그의 onload 함수안에서 로직이 동작해서 콜백으로 값을 리턴해주는 방식으로 작성했었는데, 
onload를 비동기로 기다리고, 콜백을 사용하지않고, 그냥 리턴해주는 형태로 리펙토링했음.

refactor : cropimg 함수를 콜백 전달 형태에서 return 하는형태로 변경

---

backend/src/feed/dto/request/feed.scroll.dto.ts
backend/src/feed/feed.controller.ts
backend/src/feed/feed.service.ts

기존에 15개씩 내려주던 무한 스크롤의 클라이언트의 입력값에 따라 내려주도록 구현하였다.
그리고 유효성 검사를 위해 dto을 추가하였다.
close #161

refactor: 무한 스크롤 클라이언트 입력 값만큼 내려줌

---

.github/workflows/backend-cd.yml

cd github action 스크립트를 추가하였습니다.
저희는 현재 auto-scailing을 쓰고 있습니다.
따라서, 시간에 따라 auto-scailing group 의 서버 수 및 ip가 유동적입니다.
따라서, aws의 code deploy와 유사한 ncloud의 source deploy를 사용할 예정입니다.
이를 위해서는 배포 파일을 object storlage에 올려야 하므로, 해당 과정을 cd에서 담당하고 있습니다.

chore: cd 스크립트 추가

---

backend/dataSource.ts
backend/src/feed/feed.utils.ts
backend/src/users/users.controller.ts
frontend/src/pages/SignIn/index.tsx

기존에 로그인 성공 시 최근 피드 id를 내려주었다.
이를 data를 내려주는 대신, 바로 최근 피드 url 주소로 리다이렉트 시키게 수정하였다.
closed #173

로그인 시 리다이렉트 위치 변경

---

frontend/src/index.tsx
frontend/src/pages/CreateFeed/CreateFeedButton/index.tsx
frontend/src/pages/CreateFeed/GroupMember/Suggestions.tsx
frontend/src/pages/CreateFeed/GroupMember/index.tsx
frontend/src/pages/CreateFeed/index.tsx
frontend/src/pages/CreateFeed/types.ts
frontend/src/pages/Posting/ImageSlider/ImageCard.tsx
frontend/src/pages/Posting/ImageSlider/imageQuery.ts
frontend/src/pages/Posting/ImageSlider/index.tsx
frontend/src/pages/Posting/ImageSlider/types.tsx
frontend/src/pages/Posting/index.tsx

* 관심사 분리를 위해 버튼 컴포넌트를 분리
버튼 컴포넌트는 페이지에서 업로드 할 내용을 리턴해주는 getter 함수를 인자로 받도록 설계함.
이 getter 함수에서 업로드를 해도 되는 내용인지 검증을 하고, 
업로드를 해도 된다면 업로드 인터페이스에 맞춰 리턴해주고, 
할수 없다면 토스트 메시지를 띄우고 undefined를 리턴한다.
버튼 컴포넌트에서는 getter 함수가 리턴하는 값이 undefined 라면 동작하지않고, 비어있지 않다면 동작하도록 설계했다. 
* 인터페이스를 createfeed 안 types.ts에서 보관하도록 변경
* createfeed 페이지에 분리한 버튼 컴포넌트 적용

Refactor/createfeed button&component/fe/gh

---

frontend/src/hooks/usePost.tsx
frontend/src/pages/Info/index.tsx
frontend/src/pages/Info/style.scss

중복 확인 기능을 구현하였습니다. 
만약 닉네임이 중복이거나, 올바르지 않을 시 버튼을 disable 시키도록 구현하였습니다. 
만약 서버에서 에러를 반환할 경우, 로그인 페이지로 리다이렉트 시키도록 하였습니다. 
- 이유
- 만약 카카오 로그인 과정 없이 info 페이지로 바로 접근한다면? (현재는 가능함) 
- 서버측에서 에러를 뱉고, 사용자가 아무리 닉네임을 다시 입력해봤자, 계속 에러만 가게 됨.. 
- 그럴 상황을 방지해서 일단 에러가 나면 로그인 페이지로 리다이렉트 시키도록 하였는데 다른 생각이 있으시다면 말해주세요~!

feat : 닉네임 설정 페이지 중복 확인 기능 구현

---

frontend/src/hooks/useGet.tsx
frontend/src/pages/Feed/FeedPostingList/ObserverElement/index.tsx
frontend/src/pages/Feed/FeedPostingList/index.tsx
frontend/src/pages/Feed/FeedProfile/index.tsx
frontend/src/pages/Feed/index.tsx
frontend/src/util/index.ts
frontend/src/util/validation/bool.ts

feed 페이지의 로직을 추가 및 수정하였습니다. 
- 피드 페이지 에러 로직 수정
-  '/feed' 로 접근 했을 때, 즉 feedId를 명시하지 않았을 때 404 페이지로 이동
- 올바른 feedId를 주지 않았을 때 404 페이지로 이동
- 그룹 피드의 주인(=일원)이 아닐 때 404 페이지로 이동 
- 피드의 주인이 아닐 경우, 포스팅을 클릭했을 때 '피드의 주인만 볼 수 있습니다.'라는 포스팅 띄우기
- 글쓰기 버튼이 존재할 경우 처음 포스팅을 14개만 받아오도록 수정
- 그에 따른 포스팅 끝 판단하는 로직을 변경하게 되었습니다.

feat : feed 페이지 로직 추가 및 수정

---

backend/src/users/dto/cookie.info.dto.ts

기존 api 서버와 프론트 서버의 도메인 주소(ip 주소) 가 달라 cors 문제가 발생하였다.
그런데, 만약 두 서버의 서브 도메인이 같다면,
즉 같은 도메인을 공유하고 호스트만 다르다면 cors 문제를 해결할 수 있다는 글을 보았다.
그래서 각각의 서버에 동일한 도메인(ourmemoryxoxo.me)를 등록해주고,
cookie 설정에 해당 도메인으로 `domain` 옵션을 추가해주니 잘 되었다.

fix: cors 문제 해결 위해 cookie option에 domain 추가

---

backend/src/users/users.controller.ts

쿠키 전달 과정에서 발생한 CORS 문제를 해결하기 위하여 subdomain 방식을 사용하였다.
그래서 쿠키를 생성할 때, `domain` 이라는 옵션을 추가하였는데, 로그아웃 시 `res.clearCookie` 가 안되는 이슈가 발생하였다.
찾아보니 쿠키를 삭제할 때에도 `domain`을 명시해 주면 해결되는 문제여서, `domain` 옵션을 `clearCookie` 에 추가해주었다.
[참고자료]
https://github.com/expressjs/express/issues/691

fix: 로그아웃 쿠키 삭제 안되던 문제 해결

---

backend/src/feed/dto/info.feed.dto.ts
backend/src/feed/feed.repository.ts
backend/src/feed/feed.service.ts

피드 정보 조회부분에서 테이블 3개를 조인해서 결과를 내는 쿼리문이 있었다. 
부하테스트를 진행하면서 해당하는 쿼리문에 시간이 많이 소요되고 있는 것을 파악후, 조인 연산을 줄이는 식으로 쿼리 최적화를 시도하였다. 
user-mapping table의 userId, feedId 가 pk 이므로, 해당하는 pk 값으로 한번에 원하는 값을 조회할 수 있다. 
굳이 조인연산을 사용하여 해당하는 피드의 주인이 맞는지의 유무를 확인하지 않고, user-feed-mapping table에서 한번의 search로 원하는 결과를 얻을 수 있다.

refactor: 피드 정보 조회 부분 조인 해제 후 최적화 시도

---

backend/src/custom/customValidators/nicknameValidate.ts
backend/src/entities/Feed.entity.ts
backend/src/entities/Posting.entity.ts
backend/src/users/users.facade.ts

아래와 같이 엔티티 규약을 프론트엔드와 통일하도록 수정하였다.
- 닉네임: 15자 이하
- 피드 설명: 100자 이하
- 포스팅 글: 2000자 이하(db의 letter column varchar(225) -> text 로 변경)

fix: 엔티티 규약 통일

---

backend/src/common/guard/duedate.guard.ts
backend/src/feed/feed.controller.ts
backend/src/feed/feed.repository.ts
backend/src/feed/feed.service.ts
backend/src/posting/dto/posting.scroll.dto.ts
backend/src/posting/posting.controller.ts
backend/src/posting/posting.repository.ts
backend/src/posting/posting.service.ts

- 기존에 시간 순차적으로 포스팅을 가져왔는데, 시간 역순으로 가져오게 함으로써 사용자 편의성을 높였다.
- 기존에는 해당 api를 feed repository에서 처리했고,
따라서 feed와 posting을 join 한 후, 해당하는 피드의 포스팅을 들고 오는 방식이었다면,
이제는 바로 posting repository에서 join 없이 가져오도록 하였다.(posting table의 `feedId` FK 참조)

refactor: 포스팅 무한 스크롤 api 수정

---

backend/src/custom/customError/serverError.ts
backend/src/feed/dto/members.feed.dto.ts
backend/src/feed/feed.controller.ts
backend/src/feed/feed.service.ts
backend/src/feed/user.feed.mapping.repository.ts

그룹피드의 수정 권한은 그룹 피드의 주인에게만 주어져야하기 때문에, AuthorizationGuard를 걸어주었습니다. 
user-feed-mapping 테이블과 user 테이블을 조인해서 해당하는 그룹 피드 아이디를 기준으로 select를 하도록 구현했습니다. 
이때, 그룹원을 조회할 시에는 본인의 닉네임을 제외하고 나머지 그룹원들의 닉네임과 아이디 값을 조회해야하므로, where 조건을 하나 더 추가해, user-feed-mapping 테이블의 userId 값이 본인의 id 값인 것을 제외하고 추출할 수 있도록 구현했습니다.

그룹피드 수정시 그룹 원 리스트 조회 api

---

backend/src/feed/feed.service.ts
frontend/src/components/Input/index.tsx
frontend/src/hooks/usePatch.tsx
frontend/src/index.tsx
frontend/src/pages/EditFeed/EditFeedButton/index.tsx
frontend/src/pages/EditFeed/GroupMember/Suggestions.tsx
frontend/src/pages/EditFeed/GroupMember/index.tsx
frontend/src/pages/EditFeed/index.tsx
frontend/src/pages/EditFeed/style.scss
frontend/src/pages/EditFeed/types.ts
frontend/src/pages/Feed/FeedProfile/index.tsx

피드 수정 페이지를 구현하였습니다.
<table>
<thead>
<tr>
<th width="500px">피드 사진, 소개 수정 및 그룹원 추가</th>
<th width="500px">그룹원 삭제</th>
</tr>
</thead>
<tbody>
<tr width="600px">
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
- URL은 다음과 같습니다.
- `~/EditFeed/:path/:feedId`
- `path` = `personal` or `group`
- `feedId` = `feed`의 해쉬 ID
- 피드의 기존 정보 (프로필, 제목, 소개, 그룹원) 을 불러옵니다.
- 피드의 공개일은 나타나지 않습니다.
- 만약 이미 추가된 그룹원이라면, 추가 버튼이 `disabled` 된 형태로 나타납니다. 
<table>
<thead>
<tr>
<th width="500px">이미 추가된 그룹원</th>
<th width="500px">추가되지 않은 그룹원</th>
</tr>
</thead>
<tbody>
<tr width="600px">
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
그룹 피드 수정에서 그룹원 삭제가 안되는 이슈를 발견하였습니다.
따라서 아래와 같이 변경하였습니다.
```typescript
for await (const userId of memberIdList) {
for await (const userId of prevMemberIdList) {
```
input 컴포넌트에 default value를 넣어줘야 …

[FE] 피드 수정 기능 구현

---

backend/src/image/dto/create.image.dto.ts
backend/src/image/image.repository.ts
backend/src/posting/dto/create.posting.dto.ts
backend/src/posting/posting.module.ts
backend/src/posting/posting.repository.ts
backend/src/posting/posting.service.ts
backend/src/users/users.repository.ts

기존에 포스팅 생성 api의 경우
- posting 테이블에 새로운 posting entity 삽입
- image 테이블에 posting의 등록 이미지 삽입
의 과정을 모두 posting repository의 `savePosting` 에서 트랜잭션 처리하였다.
그런데 
1. transaction 처리의 경우 service layer에서, 그리고 그 각각의 세부 db 작업을 repository 레이어에서
2. posting repository에서 image repostiory 작업도 하는 것은 동일 레이어가 서로를 참고하는 것으므로 어색하다
따라서 service layer에서 transaction을 처리하도록 수정하엿다.

refactor: 서비스 레이어에서 transacion 실행하도록 수정
